Fix command options
cypress-visual-regression/cypress-visual-regression pull request #242
Opened 2024-05-06 20:29 UTC by Zaista

fixes #239

2024-05-07 17:58 UTC, area73 commented on package.json
> +    "cy:regression": "set visual_regression_log=debug && cypress run -C cypress.regression.config.ts"
This config won't work on Mac.

The good news is that we can use  [cross-env](https://www.npmjs.com/package/cross-env) to solve the problem.

Can you try that approach?   🙏

2024-05-07 18:00 UTC, area73 requested changes
I add a comment about package scripts since they are not going to work on a Mac, but maybe we can use  [cross-env](https://www.npmjs.com/package/cross-env) to solve the problem.

2024-05-09 15:36 UTC, area73 approved these changes
  👌

2024-05-10 15:45 UTC, merged

2024-05-10 15:48 UTC, eugenet8k commented
Thank you @Zaista!